name: Run Jest Tests on Push

on:
  push:
    branches:
      - examen-parcial-1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Change permissions for Jest
        run: chmod +x node_modules/.bin/jest

      - name: Run Jest
        run: npm test
