name: Run Jest Tests on Push

on:
  push:
    branches:
      - examen-parcial-1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Actualizado a v3
      - name: Setup Node.js
        uses: actions/setup-node@v3 # Actualizado a v3
        with:
          node-version: '20' # Actualizado a Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Run Jest
        run: npm test
